version: '3.8'

services:
  odoo_app:
    image: odoo:18
    container_name: odoo_app
    ports:
      - "8069:8069"
      - "8071-8072:8071-8072"
    environment:
      - PGHOST=odoo_db
      - PGUSER=odoo
      - PGPASSWORD=odoo
      - PGDATABASE=odoo
    volumes:
      - ./custom/addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo 
    depends_on:
      - odoo_db
    restart: always
    env_file:
      - .env

  odoo_db:
    image: postgres:17
    container_name: odoo_db
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  odoo_db_data:
  odoo_data:
